### ISSUE TITLE
Atualização do GH Actions

### ISSUE THREAD

**Issue by brunomioto** [williamorim/brasileirao#3]
Certamente você sabe, mas apenas deixando isso aqui para ser resolvido quando possível, pois o action está rodando.

O GH Action não funciona devido à versão do Ubuntu rodando:

https://github.com/williamorim/brasileirao/blob/48cf4d8e554248f34cd065c2b215d583b30fc80c/.github/workflows/update_matches.yaml#L15

Segundo o github: 
```
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

**Comment by williamorim** [comment]
Obrigado, @brunomioto!
Tinha esquecido de atualizar o action.
Já está funcionando novamente.
