### ISSUE TITLE
Atualização não parece chegar ao banco "matches"

### ISSUE THREAD

**Issue by IcaroBernardes** [williamorim/brasileirao#4]
Adorei o pacote @williamorim! Eu tou fazendo uma peça interativa baseada nele, inclusive.

Eu só queria informar que parece que apesar do GA estar realizando o scrap, parece que o banco em si acessado pela função "matches" não está sendo atualizado. O scrap rodou ontem, mas os jogos da 7a rodada ainda não estão tendo seus resultados exibidos. A mim parece que o processo de scrap está todo certo, então não sei bem oq tá acontecendo.

**Comment by williamorim** [comment]
Oi, Ícaro, como vai?

Legal demais! Não sei se é a mesma peça, mas acho que vi um tweet seu sobre ela.

Sobre a atualização, eu testei aqui e as partidas de ontem constam no dataset `matches`. Um cuidado: sempre que o scraper pega novas partidas, é preciso reinstalar o pacote para baixar os arquivos atualizados. Uma alternativa é usar essa tabela a partir deste CSV, que estará sempre atualizado: 

https://raw.githubusercontent.com/williamorim/brasileirao/master/data-raw/csv/matches.csv

**Comment by IcaroBernardes** [comment]
Aaaaaaaaaah tá, entendi! Eu não tinha visto essa informação. Vou passar a pegar do csv então.

Valeu demais, William!

**Comment by IcaroBernardes** [comment]
Ah, se vc estiver considerando mudar a forma como as pessoas acessam os dados eu recomendo usar uma estratégia que o Bruno Mioto me indicou: por o banco de dados nos releases como um RDS e criar uma função de leitura que baixa ele com readRDS. Eu fiz algo assim no pacote {carnval}. Bem simples.
